export const fbPageFields = ['id', 'username', 'name', 'category', 'fan_count',
  'picture', 'events', 'about', 'emails', 'artists_we_like', 'website',
  'band_interests', 'band_members', 'general_manager', 'booking_agent',
  'press_contact', 'bio', 'hometown', 'influences', 'record_label']

export const genres = [
  'Blues': [
    'Acoustic Blues',
    'Chicago Blues',
    'Classic Blues',
    'Contemporary Blues',
    'Country Blues',
    'Delta Blues',
    'Electric Blues',
    'Ragtime Blues'
  ],
  'Classical',
  'Country': [
    'Alternative Country',
    'Americana',
    'Bluegrass',
    'Contemporary Bluegrass',
    'Contemporary Country',
    'Country Gospel',
    'Country Pop',
    'Honky Tonk',
    'Outlaw Country',
    'Traditional Bluegrass',
    'Traditional Country',
    'Urban Cowboy'
  ],
  'Electronic': [
    'Club',
    'Breakcore',
    'Breakbeat',
    'Breakstep',
    'Brostep',
    'Chillstep',
    'Deep House',
    'Dubstep',
    'Electro House',
    'Electroswing',
    'Exercise',
    'Future Garage',
    'Garage',
    'Glitch Hop ',
    'Glitch Pop',
    'Grime',
    'Hardcore',
    'Hard Dance',
    'Hi-NRG',
    'Eurodance',
    'Horrorcore',
    'House',
    'Jackin House',
    'Jungle',
    'Drum and Bass',
    'Liquid Dub',
    'Regstep',
    'Speedcore',
    'Techno',
    'Tech House',
    'Trance',
    'Trap',
    'Bop',
    'Lounge',
    'Swing',
    '2-Step',
    'Chiptune',
    'Bitpop',
    'Ambient',
    'Bassline',
    'Chillwave',
    'Crunk',
    'Downtempo',
    'Electro',
    'Electro-Swing',
    'Electronica',
    'Hardstyle',
    'IDM',
    'Experimental',
    'Industrial',
    'Trip-Hop',
    'Reggaeton',
    '8-Bit'
  ],
  'Folk': [
    'Alternative Folk',
    'Contemporary Folk',
    'Singer/Songwriter',
    'Contemporary Singer/Songwriter',
    'Indie Folk',
    'Folk-Rock',
    'Acoustic',
    'New Acoustic',
    'Traditional Folk',
    'Barbershop',
    'Doo-Wop',
    'Gregorian Chant',
    'Standards',
    'Enka'
  ],
  'Jazz': [
    'Acid Jazz',
    'Avant-Garde Jazz',
    'Bebop',
    'Big Band',
    'Blue Not',
    'Contemporary Jazz',
    'Cool',
    'Crossover Jazz',
    'Dixieland',
    'Ethio-Jazz',
    'Fusion',
    'Gypsy Jazz',
    'Hard Bop',
    'Mainstream Jazz',
    'Ragtime',
    'Smooth Jazz',
    'Trad Jazz'
  ],
  'Hip-Hop': [
    'Alternative Rap',
    'Bounce',
    'Dirty South',
    'East Coast Rap',
    'Gangsta Rap',
    'Hardcore Rap',
    'Latin Rap',
    'Old School Rap',
    'Turntablism',
    'Underground Rap',
    'West Coast Rap',
  ],
  'Pop': [
    'French Pop',
    'German Folk',
    'German Pop',
    'Indie Pop',
    'J-Pop',
    'K-Pop',
  ],
  'Reggae',
  'Rock': [
    'Art Punk',
    'Alternative Rock',
    'College Rock',
    'Crossover Thrash',
    'Christian Rock',
    'Crust Punk',
    'Dance Rock',
    'Experimental Rock',
    'Electronic Rock',
    'Folk Punk',
    'Goth Rock',
    'Grunge',
    'Hardcore Punk',
    'Hard Rock',
    'Indie Rock',
    'Lo-Fi',
    'Instrumental',
    'New Wave',
    'Progressive Rock',
    'Punk',
    'Shoegaze',
    'Steampunk',
    'Ska',
    'Acid Rock',
    'Afro Punk',
    'American Trad Rock',
    'Anatolian Rock',
    'Arena Rock',
    'Art Rock',
    'Blues-Rock',
    'British Invasion',
    'Cock Rock',
    'Death Metal',
    'Black Metal',
    'Doom Metal',
    'Glam Rock',
    'Gothic Metal',
    'Grind Core',
    'Hair Metal',
    'Math Metal',
    'Math Rock',
    'Metalcore',
    'Noise Rock',
    'Post Punk',
    'Progressive Metal',
    'Psychedelic Rock',
    'Rockabilly',
    'Roots Rock',
    'Southern Rock',
    'Spazzcore',
    'Stoner Metal',
    'Surf',
    'Technical Death Metal',
    'Tex-Mex',
    'Time Lord Rock',
    'Trash Metal',
    'Pop Punk',
    'Soft Rock',
    'Synthpop',
    'Disco',
    'Drone',
  ]
]

export const musicGenres = [

  'Karaoke',
  'Kayokyoku',
  'Latin',
  'Tango',
  'Bossa Nova',
  'Contemporary Latin',
  'Cumbia',
  'Flamenco',
  'Latin Jazz',
  'Nuevo Flamenco',
  'Pop Latino',
  'Portuguese Fado',
  'Raíces',
  'Reggaeton',
  'Regional Mexicano',
  'Salsa y Tropical',
  'New Age',
  'Environmental',
  'Healing',
  'Meditation',
  'Nature',
  'Relaxation',
  'Travel',
  'Opera',
  'Pop',
  'Britpop',
  'Bubblegum Pop',
  'Chamber Pop',
  'Dance Pop',
  'Dream Pop',
  'Electro Pop',
  'Orchestral Pop',

  'Power Pop',
  'Teen Pop',
  'Contemporary R&B',

  'Funk',
  'Modern Soul',
  'Motown',
  'Neo-Soul',
  'Northern Soul',
  'Psychedelic Soul',
  'Quiet Storm',
  'Soul',
  'Soul Blues',
  'Southern Soul',

  'Traditional Pop',
  'Vocal Pop',
  'World',
  'Africa',
  'Afro-Beat',
  'Afro-Pop',
  'Asia',
  'Australia',
  'Cajun',
  'Calypso',
  'Caribbean',
  'Carnatic',
  'Celtic',
  'Celtic Folk',
  'Contemporary Celtic',
  'Coupé-Décalé',
  'Dangdut',
  'Drinking Songs',
  'Indian Pop',
  'Traditional Celtic',
  'Worldbeat',
  'Zydeco'
]
