export const fbPageFields = ['id', 'username', 'name', 'category', 'fan_count',
  'picture', 'events', 'about', 'emails', 'artists_we_like', 'website',
  'band_interests', 'band_members', 'general_manager', 'booking_agent',
  'press_contact', 'bio', 'hometown', 'influences', 'record_label']

export const artistTypes = [
  {
    key: 'band',
    text: 'Band',
    preText: 'in a'
  },
  {
    key: 'singer-songwriter',
    text: 'Singer-Songwriter',
    preText: 'a'
  },
  {
    key: 'dj',
    text: 'DJ / Electronic Artist',
    preText: 'a'
  },
  {
    key: 'hip-hop',
    text: 'Hip-Hop / Rap Artist',
    preText: 'a'
  }
]

export const primaryGenres = [
  'Blues',
  'Classical',
  'Country',
  'Electronic',
  'Folk',
  'Jazz',
  'Hip-Hop',
  'Pop',
  'R&B',
  'Reggae',
  'Rock'
]

export const genres = [
  'Blues': [
    'Acoustic',
    'Chicago',
    'Classic',
    'Contemporary',
    'Country',
    'Delta',
    'Electric',
    'Ragtime',
    'Soul'
  ],
  'Classical',
  'Country': [
    'Alternative',
    'Americana',
    'Bluegrass',
    'Contemporary',
    'Gospel',
    'Honky Tonk',
    'Outlaw',
    'Traditional',
    'Urban Cowboy'
  ],
  'Electronic': [
    'Club',
    'Breakcore',
    'Breakbeat',
    'Breakstep',
    'Brostep',
    'Chillstep',
    'Deep House',
    'Dubstep',
    'Electro House',
    'Electroswing',
    'Exercise',
    'Future Garage',
    'Garage',
    'Glitch Hop ',
    'Glitch Pop',
    'Grime',
    'Hardcore',
    'Hard Dance',
    'Hi-NRG',
    'Eurodance',
    'Horrorcore',
    'House',
    'Jackin House',
    'Jungle',
    'Drum and Bass',
    'Liquid Dub',
    'Regstep',
    'Speedcore',
    'Techno',
    'Tech House',
    'Trance',
    'Trap',
    'Bop',
    'Lounge',
    'Swing',
    '2-Step',
    'Chiptune',
    'Bitpop',
    'Ambient',
    'Bassline',
    'Chillwave',
    'Crunk',
    'Downtempo',
    'Electro',
    'Swing',
    'Electronica',
    'Hardstyle',
    'IDM',
    'Experimental',
    'Industrial',
    'Trip-Hop',
    'Reggaeton',
    '8-Bit'
  ],
  'Folk': [
    'Acoustic',
    'Alternative',
    'Celtic',
    'Contemporary',
    'Singer/Songwriter',
    'Indie',
    'Traditional',
    'Barbershop',
    'Doo-Wop',
    'Gregorian Chant',
    'Standards',
    'Enka',
    'Punk',
    'Africa',
    'Afro',
    'Asia',
    'Australia',
    'Cajun',
    'Calypso',
    'Caribbean',
    'Carnatic',
    'Celtic',
    'Coupé-Décalé',
    'Dangdut',
    'Drinking Songs',
    'Indian',
    'Worldbeat',
    'Zydeco',
    'Kayokyoku',
    'Latin',
    'Tango',
    'Bossa Nova',
    'Cumbia',
    'Flamenco',
    'Latin Jazz',
    'Nuevo Flamenco',
    'Portuguese Fado',
    'Raíces',
    'Mexicano',
    'Salsa',
    'Tropical'
  ],
  'Jazz': [
    'Acid',
    'Avant-Garde',
    'Bebop',
    'Big Band',
    'Blue Not',
    'Contemporary',
    'Cool',
    'Crossover',
    'Dixieland',
    'Ethio',
    'Fusion',
    'Gypsy',
    'Hard Bop',
    'Mainstream',
    'Ragtime',
    'Smooth',
    'Trad'
  ],
  'Hip-Hop': [
    'Alternative',
    'Bounce',
    'Dirty South',
    'East Coast',
    'Gangster',
    'Hardcore',
    'Latin',
    'Old School',
    'Turntablism',
    'Underground',
    'West Coast',
    'Rap'
  ],
  'Pop': [
    'French',
    'German',
    'Indie',
    'Japanese',
    'Korean',
    'Britpop',
    'Bubblegum',
    'Chamber',
    'Dance',
    'Dream',
    'Electro',
    'Orchestral',
    'Power',
    'Teen',
    'Traditional',
    'Vocal',
    'Afro'
  ],
  'R&B': [
    'Contemporary',
    'Funk',
    'Modern Soul',
    'Motown',
    'Neo-Soul',
    'Northern Soul',
    'Psychedelic Soul',
    'Quiet Storm',
    'Soul',
    'Southern Soul'
  ],
  'Reggae': [
    'Roots',
    'Dancehall',
    'Dub',
    'Fusion',
    'Mento'
  ],
  'Rock': [
    'Art',
    'Alternative',
    'College',
    'Thrash',
    'Christian',
    'Crust Punk',
    'Dance',
    'Experimental',
    'Electronic',
    'Folk Punk',
    'Goth',
    'Grunge',
    'Hardcore Punk',
    'Hard',
    'Indie',
    'Lo-Fi',
    'Instrumental',
    'New Wave',
    'Progressive',
    'Punk',
    'Shoegaze',
    'Steampunk',
    'Ska',
    'Acid',
    'Afro Punk',
    'American Trad',
    'Anatolian',
    'Arena',
    'Art',
    'Blues-Rock',
    'British Invasion',
    'Cock',
    'Death Metal',
    'Black Metal',
    'Doom Metal',
    'Glam',
    'Gothic Metal',
    'Grind Core',
    'Hair Metal',
    'Math Metal',
    'Math',
    'Metalcore',
    'Noise',
    'Post Punk',
    'Progressive Metal',
    'Psychedelic',
    'Rockabilly',
    'Roots',
    'Southern',
    'Spazzcore',
    'Stoner Metal',
    'Surf',
    'Technical',
    'Tex-Mex',
    'Time Lord',
    'Trash Metal',
    'Pop Punk',
    'Soft',
    'Synth',
    'Disco',
    'Drone'
  ]
]
